### ISSUE TITLE
Consider cross-platform support\builds

### ISSUE THREAD

**Issue by brennanfee** [yaa110/nomino#1]
You should consider making this a cross-platform tool (which should be fairly easy to accomplish being in go).

Having builds available for Windows and Mac would expand the potential user base a great deal.

**Comment by yaa110** [comment]
Thank you for your feedback. links to download pre-compiled executable for MacOS and Windows were added to README. They are built automatically using github actions.

- [Linux 64bit](https://github.com/yaa110/nomino/releases/latest/download/nomino-linux-64bit)
- [MacOS 64bit](https://github.com/yaa110/nomino/releases/latest/download/nomino-macos-64bit)
- [Windows 64bit](https://github.com/yaa110/nomino/releases/latest/download/nomino-windows-64bit.exe)
