### ISSUE TITLE
AUR packaging dependency

### ISSUE THREAD

**Issue by cyqsimon** [yaa110/nomino#14]
**Describe the bug**

According to [Rust package guidelines](https://wiki.archlinux.org/title/Rust_package_guidelines#Depends), Rust packages on the AUR should declare `makedepends=('cargo')` instead of `makedepends=('rust')`. This allows `rustup`'s installed toolchains to be picked up and makes the `makepkg -dsi` workaround unnecessary.

I saw that you maintain the AUR package yourself so I thought I'd report the issue here.

**Comment by yaa110** [comment]
edited, thanks
