### ISSUE TITLE
Specifying number of jobs in `cargo build`

### ISSUE THREAD

**Issue by yonas** [yaa110/nomino#21]
https://github.com/yaa110/nomino/blob/1a2bf9fd67f9863cf2c53c0a49f97398980d4219/.github/workflows/release.yml#L30

https://github.com/yaa110/nomino/blob/1a2bf9fd67f9863cf2c53c0a49f97398980d4219/.github/workflows/release.yml#L48

I'm curious why you added the `-j` flag since cargo's default is the total number of cores.

**Comment by yaa110** [comment]
Maybe a habit from running `make` commands :)). However, it’s better to explicitly set the number of cores since the default value might change in the future (unlikely, but possible).

**Comment by yonas** [comment]
Thanks!
