### ISSUE TITLE
did 1.3.6 release get re-tagged

### ISSUE THREAD

**Issue by chenrui333** [yaa110/nomino#22]
👋 seeing some checksum changed while regression build the 1.3.6 release, raise this issue to confirm if there was some re-tagging? Thanks!

```
  Expected: 12e14d951b3fa99d17b9a0de97b7f9d9003f67ef83eb6b993623da066bc54dd4
    Actual: e6458df8bb7576bdec45af8c7d351867f736b90c6ececb0670aa6abcf1a5dee2
```

relates to 
https://github.com/Homebrew/homebrew-core/pull/199597
https://github.com/Homebrew/homebrew-core/pull/199379

**Comment by yaa110** [comment]
Unfortunately, due to deprecations in GitHub Actions, a retagging was necessary for version 1.3.6. I will create a new tag, 1.3.7, to resolve the checksum issue.

**Comment by chenrui333** [comment]
yeah, no worries, thanks for confirming it and the new tag. 🙏 

bot has already picked up the new tag, https://github.com/Homebrew/homebrew-core/pull/199682
