### ISSUE TITLE
Missing error messages

### ISSUE THREAD

**Issue by abjorck** [yaa110/nomino#8]
**Describe the bug**
When not having write permissions to files, nomino fails silently

**Command**
```bash
➜ nomino -er "(\d).(.*)" "{}-{}"
```

**Expected**
An error message that it could not do what it tried to do. (Running the same command with sudo (obviously) worked)

**Command map file (create using `-g` option)**
```json
{
doesnt matter
}
```

**Expected map file**
```json
{
tables print fine as expected
}
```

**Version (nomino -V)**
nomino 0.4.3

**Environment**
 - OS: FreeBSD 12.1-RELEASE-p10 GENERIC  amd64

**Comment by yaa110** [comment]
Fixed in v0.4.4.
