### ISSUE TITLE
Allow manually specifying search depth

### ISSUE THREAD

**Issue by l2dy** [yaa110/nomino#9]
**Is your feature request related to a problem? Please describe.**
`([^/]*)/.*` would search one more depth than I expect.

https://github.com/yaa110/nomino/blob/88ca0f6275286b2ea9695121dcf172b55ecbc6de/src/input/source.rs#L23-L24

**Describe the solution you'd like**
Add a `--max-depth` and/or `--depth` option to control search depth of subdirectories.

**Comment by yaa110** [comment]
`--depth` argument added in [version 0.5.0](https://github.com/yaa110/nomino/releases/tag/0.5.0) to overwrite inferred subdirectory depth value in `regex` mode.

**Comment by l2dy** [comment]
Thank you!
